spring:
  datasource:
    url: jdbc:h2:mem:hearbusan;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    defer-datasource-initialization: true   # data.sql 을 DDL 이후 실행
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true      # http://localhost:8080/h2-console

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/hearbusan?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
